---
apiVersion: v1
kind: Service
metadata:
  name: mapper
  labels:
    app: mapper
spec:
  type: NodePort
  selector:
    app: mapper
  ports:
    - protocol: TCP
      port: 9000
      name: http
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapper
spec:
  selector:
    matchLabels:
      app: mapper
  replicas: 1
  template:
    metadata:
      labels:
        app: mapper
    spec:
      containers:
        - name: mapper
          image: joltmapper:latest
          imagePullPolicy: Never #Added this since I am getting an error
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 9000
            timeoutSeconds: 1
            #periodSeconds: 60 - defaults for 10